# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies

      - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      #
      #  TODO -- Reactivate after Integration Test issues have been resolved

      - run: mvn integration-test

      - run: mvn sonar:sonar -Dsonar.projectKey=GreenButtonAlliance_OpenESPI-DataCustodian-java -Dsonar.organization=greenbuttonalliance -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2ddd7468eede6ec7c1846bf610c2699d9f81b87d

