# Development PostgreSQL Profile Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datacustodian?createDatabaseIfNotExist=true
    username: espi
    password: espi123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: DataCustodianHikariCP
      auto-commit: false
      connection-test-query: SELECT 1
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        
  flyway:
    locations: classpath:db/migration/postgresql
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# Development-specific logging
logging:
  level:
    org.greenbuttonalliance.espi: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
server:
  port: 8081

espi:
  datacustodian:
    base-url: http://localhost:8081/DataCustodian
  authorization-server:
    issuer-uri: http://localhost:8080
    jwk-set-uri: http://localhost:8080/.well-known/jwks.json