# Local Development H2 Profile Configuration
spring:
  datasource:
    url: jdbc:h2:mem:datacustodian;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: DataCustodianHikariCP
      auto-commit: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
        
  flyway:
    enabled: false  # Disable Flyway for H2 development

# Development-specific logging
logging:
  level:
    org.greenbuttonalliance.espi: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
server:
  port: 8081

espi:
  datacustodian:
    base-url: http://localhost:8081/DataCustodian
  authorization-server:
    issuer-uri: http://localhost:8080
    jwk-set-uri: http://localhost:8080/.well-known/jwks.json